# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::V8
          needs: check
          
      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install courier font on Windows
        # to fix PDF error "Cannot find pcrr8t.mf."
        if: runner.os == 'Windows'
        run: |
          tlmgr --version
          tlmgr install courier
                    
      - uses: r-lib/actions/check-r-package@v2
        continue-on-error: true
        with:
          upload-snapshots: true
          build_args: 'c("--compact-vignettes=gs+qpdf")'
          args: 'c("--as-cran")'

      - name: Check log PDF file on Windows
        if: runner.os == 'Windows'
        run: |
          $codeR = @'
            print("R is starting")
            print("second print")
            print(sessionInfo())
            Rd2pdf_opts <- c("--no-preview", "--internals")
            build_dir <- "D:/a/PackageTestLatexErrorsR/PackageTestLatexErrorsR/check/PackageTestLatexErrorsR.Rcheck/"
            pkgname <- "PackageTestLatexErrorsR"
            man_file <- paste0(pkgname, "-manual.pdf ")
            print("preparing to remove file if it exists")
            ## precautionary remove in case some other attempt left it behind
            if(file.exists(man_file)) {
              print("man_file already exists")
              unlink(man_file)
              print("man_file now deleted")
            } else {
              print("no man_file found")
            }
            print("preparing args")
            args <- c( "Rd2pdf ", Rd2pdf_opts,
                      paste0("--build-dir=", shQuote(build_dir)),
                      "--no-clean", "-o ", man_file 
                      , shQuote(build_dir)
                      )
            
            print("running Rd2pdf...")
            res <- tools:::run_Rcmd(args,  "Rdlatex.log", timeout = "")
            print("Rd2pdf is finished, result is:")
            print(res)

            print("preparing args without build_dir")
            args <- c( "Rd2pdf ", Rd2pdf_opts,
                      paste0("--build-dir=", shQuote(build_dir)),
                      "--no-clean", "-o ", man_file
                      )
            
            print("running Rd2pdf...")
            res <- tools:::run_Rcmd(args,  "Rdlatex.log", timeout = "")
            print("Rd2pdf is finished, result is:")
            print(res)
            
            # print("preparing args without build_dir nor space")
            # args <- c("Rd2pdf ", Rd2pdf_opts,
            #           "--build-dir=", build_dir,
            #           "--no-clean", "-o", man_file
            #           )
            #           
            # print("running Rd2pdf from R...")
            # res <- tools:::..Rd2pdf(args[-1])
            # print("Rd2pdf is finished, result is:")
            # print(res)
            # 
            # # This produces the error: 
            # # Error: Error in dir.create(build_dir, FALSE) : zero-length 'path' argument
            #
            
            print("preparing args with build_dir but no space")
            cat("build_dir=", build_dir, "\n")
            args <- c(Rd2pdf_opts,
                      "--build-dir=", build_dir,
                      "--no-clean", "-o", man_file, build_dir
                      )
                      
            print("running Rd2pdf from R...")
            res <- tools:::..Rd2pdf(args)
            print("Rd2pdf is finished, result is:")
            print(res)
            
            # latex_log <- file.path(build_dir, "Rd2.log")
            # tools:::.get_LaTeX_errors_from_log_file(file(latex_log)) |> print()
          '@
          # Write to a temporary file
          $tempScript = New-TemporaryFile | Rename-Item -NewName { $_ -replace '\.tmp$', '.R' } -PassThru
          Set-Content -Path $tempScript.FullName -Value $codeR

          # Run the script
          Rscript $tempScript.FullName
